# Limine configuration file for Nexus.
# See: https://github.com/Limine-Bootloader/limine-protocol (CONFIG.md)

timeout: 3

/Nexus
    protocol: limine
    kernel_path: boot():/boot/kernel
    module_path: boot():/boot/initrd.tar

/Nexus (serial debug verbose)
    protocol: limine
    kernel_path: boot():/boot/kernel
    module_path: boot():/boot/initrd.tar
    cmdline: debug=serial

/Nexus (single CPU / SMP disabled)
    protocol: limine
    kernel_path: boot():/boot/kernel
    module_path: boot():/boot/initrd.tar
    cmdline: nosmp

/Nexus (self-test)
    protocol: limine
    kernel_path: boot():/boot/kernel
    module_path: boot():/boot/initrd.tar
    cmdline: selftest

/Nexus (ring-0 kernel shell)
    protocol: limine
    kernel_path: boot():/boot/kernel
    module_path: boot():/boot/initrd.tar
    cmdline: kshell
