/* GENERATED FILE -- do not edit directly.
 * Canonical source: abi/task_info.h
 * Regenerated by: scripts/sync-abi.sh (via `make sync-abi`)
 * If you need to change this ABI, edit the canonical copy and
 * re-run `make sync-abi` (the normal build does this for you).
 */
#ifndef NEXUS_TASK_INFO_H
#define NEXUS_TASK_INFO_H

#include <stdint.h>

/*
 * THIS is the single canonical copy -- see abi/syscall_nr.h's header
 * comment for how `make sync-abi` mirrors it into kernel/src/abi/ and
 * userland/include/ as generated, banner-marked files.
 *
 * The record SYS_ps (see abi/syscall_nr.h) fills at its user-supplied
 * output pointer -- one call, one task, in registry order (same order
 * `ps` in the kernel shell walks). Deliberately flat/POD, fixed
 * width, no pointers: this crosses the user/kernel boundary via a
 * plain copy_to_user(), so anything here has to be safe to blit
 * byte-for-byte.
 */

#define NX_TASK_NAME_MAX 32

/* Mirrors enum task_state in sched/sched.h numerically (TASK_READY=0
 * .. TASK_DEAD=5) -- kept as a plain uint32_t rather than including
 * sched.h here, since this header has to compile standalone in
 * userland where sched.h doesn't exist. No compile-time link between
 * the two -- if sched.h's enum order ever changes, this silently goes
 * stale; `make sync-abi` only keeps the two build trees in sync with
 * each other, it can't catch that. */
typedef struct {
  uint64_t pid;
  char name[NX_TASK_NAME_MAX];
  uint32_t state;
  uint32_t is_user;
} nx_task_info_t;

#endif /* NEXUS_TASK_INFO_H */
