#!/bin/sh
# Regenerates the kernel-tree and userland-tree copies of Nexus's
# shared syscall ABI headers from the single canonical source in
# abi/. Both kernel/ and userland/ stay freestanding, standalone
# build trees with no shared installed sysroot (see docs/BUILD_LAYOUT.md
# for why that split still exists) -- this script is what removes the
# old failure mode of hand-editing one copy and forgetting the other.
#
# Run automatically as a prerequisite of both `kernel` and `userland`
# build targets (see the top-level Makefile) -- you normally never
# need to run this by hand. `make check-abi` verifies nobody hand-
# edited a generated copy instead of abi/ itself.
set -eu
cd "$(dirname "$0")/.."

sync_one() {
  src="$1"
  dst="$2"
  mkdir -p "$(dirname "$dst")"
  tmp="$dst.tmp.$$"
  {
    echo "/* GENERATED FILE -- do not edit directly."
    echo " * Canonical source: $src"
    echo " * Regenerated by: scripts/sync-abi.sh (via \`make sync-abi\`)"
    echo " * If you need to change this ABI, edit the canonical copy and"
    echo " * re-run \`make sync-abi\` (the normal build does this for you)."
    echo " */"
    cat "$src"
  } > "$tmp"

  # Only replace dst (and thus bump its mtime) if content actually
  # changed -- sync-abi runs unconditionally on every build (see the
  # kernel/userland Makefiles), so touching every copy's mtime on
  # every invocation would force a full rebuild every time regardless
  # of whether abi/ actually changed.
  if [ -f "$dst" ] && cmp -s "$tmp" "$dst"; then
    rm -f "$tmp"
  else
    mv -f "$tmp" "$dst"
  fi
}

sync_one abi/syscall_nr.h kernel/src/abi/syscall_nr.h
sync_one abi/task_info.h  kernel/src/abi/task_info.h
sync_one abi/syscall_nr.h userland/include/syscall_nr.h
sync_one abi/task_info.h  userland/include/task_info.h

echo "[sync-abi] kernel/src/abi/ and userland/include/ refreshed from abi/"
